-- ============================================================
-- 00. CONTEXTO DE TRABAJO
-- ============================================================
CREATE OR REPLACE DATABASE TALLER_DATO_DECISION;
CREATE OR REPLACE SCHEMA TALLER_DATO_DECISION.BRONZE;
CREATE OR REPLACE SCHEMA TALLER_DATO_DECISION.SILVER;
CREATE OR REPLACE SCHEMA TALLER_DATO_DECISION.GOLD;

USE DATABASE TALLER_DATO_DECISION;
USE SCHEMA BRONZE;

-- ============================================================
-- 01. FILE FORMAT Y STAGE
-- ============================================================
CREATE OR REPLACE FILE FORMAT FF_CSV_COMPLUBEER
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE
  ENCODING = 'UTF8';

CREATE OR REPLACE STAGE STG_COMPLUBEER
  FILE_FORMAT = FF_CSV_COMPLUBEER;

-- Subir los cuatro CSV al stage desde la interfaz de Snowflake.
-- Después comprobar:
LIST @STG_COMPLUBEER;

-- ============================================================
-- 02. CAPA BRONZE: TABLAS BRUTAS
-- Todas las columnas se cargan como STRING para controlar el tipado en Silver.
-- ============================================================
CREATE OR REPLACE TABLE BRONZE.RAW_VENTAS (
  ID_VENTA STRING,
  FECHA_VENTA STRING,
  ANIO STRING,
  MES STRING,
  ID_PRODUCTO STRING,
  REGION STRING,
  CIUDAD STRING,
  CANAL STRING,
  VOLUMEN_HL STRING,
  INGRESOS_EUR STRING,
  DESCUENTO_EUR STRING,
  ORIGEN_FICHERO STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_PRODUCTOS (
  ID_PRODUCTO STRING,
  PRODUCTO STRING,
  FAMILIA STRING,
  ESTILO STRING,
  ABV STRING,
  IBU STRING,
  FORMATO STRING,
  COSTE_UNITARIO_EUR_HL STRING,
  PRECIO_REFERENCIA_EUR_HL STRING,
  LANZAMIENTO STRING,
  ACTIVO STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_OBJETIVOS (
  ANIO STRING,
  MES STRING,
  REGION STRING,
  CANAL STRING,
  ID_PRODUCTO STRING,
  OBJETIVO_HL STRING,
  OBJETIVO_EUR STRING,
  OBJETIVO_MARGEN_PCT STRING,
  PRIORIDAD STRING
);

CREATE OR REPLACE TABLE BRONZE.RAW_CANALES (
  CANAL_RAW STRING,
  CANAL_NORMALIZADO STRING,
  TIPO_CANAL STRING,
  SEGMENTO STRING,
  ZONA_COMERCIAL STRING,
  PRIORIDAD_COMERCIAL STRING
);

COPY INTO BRONZE.RAW_VENTAS
FROM @STG_COMPLUBEER/ventas_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

COPY INTO BRONZE.RAW_PRODUCTOS
FROM @STG_COMPLUBEER/productos_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

COPY INTO BRONZE.RAW_OBJETIVOS
FROM @STG_COMPLUBEER/objetivos_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

COPY INTO BRONZE.RAW_CANALES
FROM @STG_COMPLUBEER/canales_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

-- Validaciones de carga
SELECT 'RAW_VENTAS' AS tabla, COUNT(*) AS registros FROM BRONZE.RAW_VENTAS
UNION ALL SELECT 'RAW_PRODUCTOS', COUNT(*) FROM BRONZE.RAW_PRODUCTOS
UNION ALL SELECT 'RAW_OBJETIVOS', COUNT(*) FROM BRONZE.RAW_OBJETIVOS
UNION ALL SELECT 'RAW_CANALES', COUNT(*) FROM BRONZE.RAW_CANALES;
